# Generated by Django 5.2.14 on 2026-05-16 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('events', '0001_initial'),
        ('iot_config', '0001_initial'),
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='telemetry.measurement'),
        ),
        migrations.AddField(
            model_name='event',
            name='metric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='iot_config.metricdefinition'),
        ),
        migrations.AddField(
            model_name='event',
            name='raw_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='telemetry.rawmessage'),
        ),
        migrations.AddField(
            model_name='event',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='assets.sensor'),
        ),
        migrations.AddField(
            model_name='event',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='assets.site'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['site', 'status'], name='events_even_site_id_a83824_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['asset', 'status'], name='events_even_asset_i_c07730_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['device', 'status'], name='events_even_device__c3d82a_idx'),
        ),
    ]
