# Generated by Django 5.2.14 on 2026-05-16 14:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('active', 'Active'), ('inactive', 'Inactive'), ('warning', 'Warning'), ('error', 'Error'), ('offline', 'Offline')], default='unknown', max_length=32)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_measurement_at', models.DateTimeField(blank=True, null=True)),
                ('last_temperature_c', models.FloatField(blank=True, null=True)),
                ('last_voltage_v', models.FloatField(blank=True, null=True)),
                ('last_current_a', models.FloatField(blank=True, null=True)),
                ('last_power_w', models.FloatField(blank=True, null=True)),
                ('last_battery_soc_pct', models.FloatField(blank=True, null=True)),
                ('active_anomaly_count', models.PositiveIntegerField(default=0)),
                ('has_active_anomaly', models.BooleanField(default=False)),
                ('state_payload', models.JSONField(blank=True, default=dict)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='assets.asset')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_states', to='assets.device')),
            ],
            options={
                'verbose_name': 'Asset State',
                'verbose_name_plural': 'Asset States',
            },
        ),
    ]
