# Generated by Django 5.2.14 on 2026-05-16 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('digital_twin', '0001_initial'),
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetstate',
            name='last_raw_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_states', to='telemetry.rawmessage'),
        ),
        migrations.AddField(
            model_name='assetstate',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_states', to='assets.site'),
        ),
        migrations.AddIndex(
            model_name='assetstate',
            index=models.Index(fields=['status'], name='digital_twi_status_c78977_idx'),
        ),
        migrations.AddIndex(
            model_name='assetstate',
            index=models.Index(fields=['last_seen_at'], name='digital_twi_last_se_2939e1_idx'),
        ),
        migrations.AddIndex(
            model_name='assetstate',
            index=models.Index(fields=['has_active_anomaly'], name='digital_twi_has_act_1ae26b_idx'),
        ),
        migrations.AddIndex(
            model_name='assetstate',
            index=models.Index(fields=['site', 'status'], name='digital_twi_site_id_75518e_idx'),
        ),
    ]
