# Generated by Django 5.2.14 on 2026-05-16 16:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('iot_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatorScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('default_status', models.CharField(default='charging', max_length=32)),
                ('interval_seconds', models.PositiveIntegerField(default=60)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulator_scenarios', to='assets.site')),
            ],
            options={
                'verbose_name': 'Simulator Scenario',
                'verbose_name_plural': 'Simulator Scenarios',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SimulatorRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=32)),
                ('messages_published', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='simulator.simulatorscenario')),
            ],
            options={
                'verbose_name': 'Simulator Run',
                'verbose_name_plural': 'Simulator Runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulatorScenarioDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('status_override', models.CharField(blank=True, max_length=32)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_devices', to='assets.device')),
                ('device_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario_devices', to='iot_config.deviceprofile')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_devices', to='simulator.simulatorscenario')),
            ],
            options={
                'verbose_name': 'Simulator Scenario Device',
                'verbose_name_plural': 'Simulator Scenario Devices',
                'ordering': ['scenario', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SimulatorMetricProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('base_value', models.FloatField()),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('noise_amplitude', models.FloatField(default=0.0)),
                ('generation_mode', models.CharField(choices=[('constant', 'Constant'), ('random_noise', 'Random Noise'), ('random_walk', 'Random Walk')], default='constant', max_length=32)),
                ('is_enabled', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_profiles', to='iot_config.metricdefinition')),
                ('scenario_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_profiles', to='simulator.simulatorscenariodevice')),
            ],
            options={
                'verbose_name': 'Simulator Metric Profile',
                'verbose_name_plural': 'Simulator Metric Profiles',
                'ordering': ['scenario_device', 'sort_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='simulatorscenariodevice',
            constraint=models.UniqueConstraint(fields=('scenario', 'device'), name='unique_simulator_scenario_device'),
        ),
        migrations.AddConstraint(
            model_name='simulatormetricprofile',
            constraint=models.UniqueConstraint(fields=('scenario_device', 'metric'), name='unique_simulator_metric_profile'),
        ),
    ]
