# Generated by Django 5.2.14 on 2026-05-16 14:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('timezone', models.CharField(default='Europe/Riga', max_length=64)),
                ('is_demo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=256)),
                ('asset_type', models.CharField(choices=[('charger', 'Charger'), ('battery', 'Battery'), ('sensor_node', 'Sensor Node'), ('infrastructure_node', 'Infrastructure Node'), ('other', 'Other')], default='other', max_length=32)),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('active', 'Active'), ('inactive', 'Inactive'), ('warning', 'Warning'), ('error', 'Error'), ('offline', 'Offline')], default='unknown', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=128)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='assets.asset')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assets.site')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['site', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('device_uid', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('device_type', models.CharField(blank=True, max_length=64)),
                ('is_simulated', models.BooleanField(default=False)),
                ('expected_interval_seconds', models.PositiveIntegerField(default=60)),
                ('firmware_version', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('active', 'Active'), ('inactive', 'Inactive'), ('warning', 'Warning'), ('error', 'Error'), ('offline', 'Offline')], default='unknown', max_length=32)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='assets.asset')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='assets.site')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['device_uid'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=256)),
                ('sensor_type', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='assets.device')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensors',
                'ordering': ['device', 'code'],
                'constraints': [models.UniqueConstraint(fields=('device', 'code'), name='unique_sensor_device_code')],
            },
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('site', 'code'), name='unique_asset_site_code'),
        ),
    ]
