# Generated by Django 5.2.14 on 2026-05-17 09:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('iot_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensor_metrics', to='iot_config.metricdefinition')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_metrics', to='assets.sensor')),
            ],
            options={
                'verbose_name': 'Sensor Metric',
                'verbose_name_plural': 'Sensor Metrics',
                'ordering': ['sensor', 'sort_order', 'metric__key'],
            },
        ),
        migrations.AddField(
            model_name='sensor',
            name='metrics',
            field=models.ManyToManyField(blank=True, related_name='sensors', through='assets.SensorMetric', to='iot_config.metricdefinition'),
        ),
        migrations.AddIndex(
            model_name='sensormetric',
            index=models.Index(fields=['metric'], name='assets_sens_metric__20f475_idx'),
        ),
        migrations.AddConstraint(
            model_name='sensormetric',
            constraint=models.UniqueConstraint(fields=('sensor', 'metric'), name='unique_sensor_metric_sensor_metric'),
        ),
    ]
