"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
import os

BASE_DIR = Path(__file__).resolve().parent.parent.parent

env = environ.Env(
    DEBUG=(bool, False),
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])


# Application definition

INSTALLED_APPS = [
    "daphne",
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "rest_framework",
    "django_filters",
    "channels",

    "apps.core",
    "apps.accounts",
    "apps.assets",
    "apps.iot_config",
    "apps.simulator",
    "apps.mqtt_ingestion",
    "apps.telemetry",
    "apps.digital_twin",
    "apps.analytics",
    "apps.events",
    "apps.api",
    "apps.dashboard",
    "apps.reports",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = "config.asgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": env("PG_SC_HOST"),
        "PORT": env("PG_SC_PORT"),
        "NAME": env("PG_SC_DATABASE"),
        "USER": env("PG_SC_USER"),
        "PASSWORD": env("PG_SC_PASSWORD"),
        "OPTIONS": {
            "sslmode": env("PG_SC_SSLMODE", default="prefer"),
        },
    }
}

scooter_cert_file = os.getenv("PG_SC_SSLROOTCERT")
if scooter_cert_file:
    DATABASES["default"]["OPTIONS"]["sslrootcert"] = os.path.join(BASE_DIR, scooter_cert_file)

REDIS_URL = env("REDIS_URL", default="redis://redis:6379/0")

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
        },
    },
}

# Environment tag used in MQTT topic segments: smt/{SMT_ENV}/...
SMT_ENV = env("SMT_ENV", default="dev")

# MQTT worker settings
MQTT_HOST = env("MQTT_HOST", default="mqtt")
MQTT_PORT = env.int("MQTT_PORT", default=1883)
MQTT_USERNAME = env("MQTT_USERNAME", default="")
MQTT_PASSWORD = env("MQTT_PASSWORD", default="")
MQTT_KEEPALIVE_SECONDS = env.int("MQTT_KEEPALIVE_SECONDS", default=60)
MQTT_CLIENT_ID = env("MQTT_CLIENT_ID", default="smt-django-mqtt-worker")
MQTT_SUBSCRIBE_TOPICS = env.list(
    "MQTT_SUBSCRIBE_TOPICS",
    default=["smt/+/+/+/+/telemetry"],
)

# MQTT simulator publisher credentials (separate from the worker subscriber)
MQTT_SIMULATOR_USERNAME = env("MQTT_SIMULATOR_USERNAME", default="smt_simulator")
MQTT_SIMULATOR_PASSWORD = env("MQTT_SIMULATOR_PASSWORD", default="")


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'lv-LV'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
