"""
Dashboard shell views (Phase 6) + staged operator workflow (Phase 7).

* The original dashboard is a thin server-rendered shell that delegates
  data to the read-only Phase 6 API.
* Phase 7 Task 3 added a single-page asset create form. **Phase 7 Task
  3B** replaces it with a *staged* workflow: each stage has its own
  route, its own form, and its own ``transaction.atomic`` so a failure
  in stage N never destroys progress from stages 1..N-1.

The technical identifiers (``Asset.code``, ``Device.device_uid``,
``Sensor.code``, ``ThresholdRule.code``) are no longer typed by the
operator — they are generated by
:mod:`apps.assets.services.identifiers`.
"""

from __future__ import annotations

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views import View
from django.views.generic import TemplateView

from apps.analytics.models import ThresholdRule
from apps.assets.models import Asset, Device, Sensor, SensorMetric, Site
from apps.events.models import Event, EventStatus, EventType, Severity
from apps.assets.services.identifiers import (
    create_asset_with_unique_code,
    create_device_with_unique_uid,
    create_sensor_with_unique_code,
    create_threshold_rule_with_unique_code,
)
from apps.dashboard.forms import (
    METRIC_MODE_CHOICES,
    METRIC_MODE_EXISTING,
    METRIC_MODE_NEW,
    METRIC_MODE_PRESET,
    SITE_MODE_EXISTING,
    SITE_MODE_NEW,
    THRESHOLD_MODE_MANUAL,
    THRESHOLD_MODE_NONE,
    THRESHOLD_MODE_PRESET,
    THRESHOLD_SCOPE_CHOICES,
    AssetCreateStageForm,
    DeviceAttachStageForm,
    DeviceCreateStageForm,
    ThresholdRuleEditForm,
    SensorCreateStageForm,
    SensorMetricStageForm,
)
from apps.iot_config.models import MetricDefinition


# Charts shown on the asset detail page. Kept here (not in the template)
# so the test suite can assert exactly which metrics the page advertises
# without scraping JavaScript.
ASSET_DETAIL_CHART_METRICS = (
    "temperature_c",
    "voltage_v",
    "power_w",
    "battery_soc_pct",
)


# ── Phase 6 read-only shell views ────────────────────────────────────────────

class OverviewView(LoginRequiredMixin, TemplateView):
    template_name = "dashboard/overview.html"
    http_method_names = ["get", "head", "options"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["dashboard_config"] = {
            "endpoints": {
                "overview": reverse("api-overview"),
                "overviewAssets": reverse("api-overview-assets"),
                "overviewEvents": reverse("api-overview-events"),
                "overviewTelemetry": reverse("api-overview-telemetry"),
                "overviewSimulator": reverse("api-overview-simulator"),
                "health": reverse("api-health"),
            },
            "assetSummaryUrlTemplate": reverse(
                "asset-summary", kwargs={"pk": "__CODE__"},
            ),
            "assetDetailUrlTemplate": reverse(
                "dashboard:asset-detail",
                kwargs={"asset_identifier": "__CODE__"},
            ),
            "autoRefreshIntervalSeconds": 30,
        }
        return context


class AssetDetailView(LoginRequiredMixin, TemplateView):
    template_name = "dashboard/asset_detail.html"
    http_method_names = ["get", "head", "options"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        identifier = kwargs.get("asset_identifier", "")
        context["asset_identifier"] = identifier
        summary_url = reverse("asset-summary", kwargs={"pk": identifier})
        measurements_url = reverse("asset-measurements", kwargs={"pk": identifier})
        events_url = reverse("asset-events", kwargs={"pk": identifier})
        chart_url_template = measurements_url + "?metric=__METRIC__&limit=100"
        # ``configure_url`` is rendered as a link in the asset detail
        # header; it is None when the path segment is a UUID (no easy
        # mapping back to a configure URL) or when the asset doesn't
        # exist yet (the shell still renders for a 404 banner).
        configure_url = None
        try:
            asset = Asset.objects.only("code").get(code=identifier)
            configure_url = reverse(
                "dashboard:asset-configure",
                kwargs={"asset_code": asset.code},
            )
        except Asset.DoesNotExist:
            pass
        context["configure_url"] = configure_url
        context["asset_detail_config"] = {
            "assetIdentifier": identifier,
            "summaryUrl": summary_url,
            "measurementsUrl": measurements_url + "?limit=20",
            "eventsUrl": events_url + "?limit=20",
            "chartUrlTemplate": chart_url_template,
            "chartMetrics": list(ASSET_DETAIL_CHART_METRICS),
            "dashboardOverviewUrl": reverse("dashboard:overview"),
            "autoRefreshIntervalSeconds": 30,
        }
        return context


# ── Assets list ──────────────────────────────────────────────────────────────

@login_required
def assets_list_view(request):
    assets = (
        Asset.objects
        .select_related("site")
        .prefetch_related("devices")
        .order_by("site__code", "code")
    )
    rows = []
    for asset in assets:
        state = getattr(asset, "state", None)
        rows.append({
            "code": asset.code,
            "name": asset.name,
            "site_code": asset.site.code if asset.site_id else "",
            "asset_type": asset.get_asset_type_display(),
            "status": asset.get_status_display(),
            "status_value": asset.status,
            "devices_count": asset.devices.count(),
            "active_anomaly_count": (
                getattr(state, "active_anomaly_count", 0) if state else 0
            ),
            "detail_url": reverse(
                "dashboard:asset-detail",
                kwargs={"asset_identifier": asset.code},
            ),
            "configure_url": reverse(
                "dashboard:asset-configure",
                kwargs={"asset_code": asset.code},
            ),
            "summary_api_url": reverse(
                "asset-summary", kwargs={"pk": asset.code},
            ),
        })
    return render(request, "dashboard/assets_list.html", {
        "rows": rows,
        "create_url": reverse("dashboard:asset-create"),
    })


# ── Helpers ──────────────────────────────────────────────────────────────────

def _get_asset_or_404(asset_code: str) -> Asset:
    return get_object_or_404(
        Asset.objects.select_related("site"), code=asset_code,
    )


def _get_device_or_404(asset: Asset, device_uid: str) -> Device:
    return get_object_or_404(
        Device.objects.select_related("asset", "site"),
        device_uid=device_uid, asset=asset,
    )


def _get_sensor_or_404(device: Device, sensor_code: str) -> Sensor:
    return get_object_or_404(
        Sensor.objects.select_related("device"),
        device=device, code=sensor_code,
    )


# ── Stage 1: Asset create ────────────────────────────────────────────────────

class AssetCreateStageView(LoginRequiredMixin, View):
    """Stage 1 — create the Asset (and optionally a new Site) only."""

    template_name = "dashboard/asset_create.html"

    def get(self, request):
        return render(request, self.template_name, {
            "form": AssetCreateStageForm(),
        })

    def post(self, request):
        form = AssetCreateStageForm(request.POST)
        if not form.is_valid():
            return render(
                request, self.template_name,
                {"form": form, "has_errors": True}, status=400,
            )
        try:
            asset = self._commit(form)
        except Exception as exc:  # noqa: BLE001 — surface to the form
            form.add_error(None, str(exc))
            return render(
                request, self.template_name,
                {"form": form, "has_errors": True}, status=400,
            )
        messages.success(
            request,
            f"Aktīvs '{asset.code}' veiksmīgi izveidots. "
            f"Turpiniet konfigurāciju zemāk.",
        )
        return redirect(
            reverse("dashboard:asset-configure",
                    kwargs={"asset_code": asset.code})
        )

    @transaction.atomic
    def _commit(self, form: AssetCreateStageForm) -> Asset:
        site = self._resolve_site(form)
        return create_asset_with_unique_code(
            site=site,
            name=form.cleaned_data["name"].strip(),
            asset_type=form.cleaned_data["asset_type"],
            status=form.cleaned_data.get("status") or "unknown",
            description=(form.cleaned_data.get("description") or ""),
            latitude=form.cleaned_data.get("latitude"),
            longitude=form.cleaned_data.get("longitude"),
            external_id=(form.cleaned_data.get("external_id") or ""),
        )

    @staticmethod
    def _resolve_site(form: AssetCreateStageForm) -> Site:
        if form.cleaned_data["site_mode"] == SITE_MODE_EXISTING:
            return form.cleaned_data["existing_site"]
        return Site.objects.create(
            code=form.cleaned_data["new_site_code"].strip(),
            name=form.cleaned_data["new_site_name"].strip(),
            description=(form.cleaned_data.get("new_site_description") or ""),
            address=(form.cleaned_data.get("new_site_address") or ""),
            latitude=form.cleaned_data.get("new_site_latitude"),
            longitude=form.cleaned_data.get("new_site_longitude"),
            timezone=form.cleaned_data["new_site_timezone"],
            is_demo=bool(form.cleaned_data.get("new_site_is_demo")),
        )


# ── Configure page (stage hub) ───────────────────────────────────────────────

@login_required
def asset_configure_view(request, asset_code: str):
    """
    Server-rendered configuration hub for one ``Asset``.

    Shows the current configuration state (devices, sensors,
    sensor-metrics, threshold rules) and offers links into each Stage 2-4
    sub-form. Read-only — the page itself does not mutate anything.
    """
    asset = _get_asset_or_404(asset_code)

    devices = (
        asset.devices
        .select_related("site")
        .prefetch_related(
            "sensors__sensor_metrics__metric",
        )
        .order_by("device_uid")
    )

    # Build a per-device view tree so the template stays simple.
    device_rows = []
    for device in devices:
        sensor_rows = []
        for sensor in device.sensors.all().order_by("code"):
            sm_rows = [
                {
                    "metric_key": sm.metric.key,
                    "metric_unit": sm.metric.unit,
                    "is_required": sm.is_required,
                    "sort_order": sm.sort_order,
                }
                for sm in sensor.sensor_metrics.all()
            ]
            sensor_rows.append({
                "sensor": sensor,
                "sensor_metrics": sm_rows,
                "add_metric_url": reverse(
                    "dashboard:sensor-metric-create",
                    kwargs={
                        "asset_code": asset.code,
                        "device_uid": device.device_uid,
                        "sensor_code": sensor.code,
                    },
                ),
            })
        device_rows.append({
            "device": device,
            "sensor_rows": sensor_rows,
            "add_sensor_url": reverse(
                "dashboard:sensor-create",
                kwargs={
                    "asset_code": asset.code,
                    "device_uid": device.device_uid,
                },
            ),
        })

    # All threshold rules **reachable** from this asset: sensor/device/asset
    # bound rules whose target is under this asset, plus site-scope rules
    # whose site == this asset's site. Global rules are intentionally not
    # listed — they're cross-asset by definition and live in admin.
    from django.db.models import Q
    from apps.analytics.models import ThresholdRuleScope

    threshold_rules_qs = (
        ThresholdRule.objects
        .select_related("metric", "sensor", "sensor__device",
                        "device", "asset", "site")
        .filter(
            Q(
                scope_level=ThresholdRuleScope.SENSOR,
                sensor__device__asset=asset,
            )
            | Q(
                scope_level=ThresholdRuleScope.DEVICE,
                device__asset=asset,
            )
            | Q(scope_level=ThresholdRuleScope.ASSET, asset=asset)
            | Q(scope_level=ThresholdRuleScope.SITE, site=asset.site),
        )
        .order_by("sort_order", "code")
    )
    # Materialise into view-friendly rows so the template doesn't have
    # to compute an edit URL per row.
    threshold_rules = []
    for r in threshold_rules_qs:
        threshold_rules.append({
            "rule": r,
            "edit_url": reverse(
                "dashboard:threshold-rule-edit",
                kwargs={"asset_code": asset.code, "rule_code": r.code},
            ),
        })

    return render(request, "dashboard/asset_configure.html", {
        "asset": asset,
        "site": asset.site,
        "device_rows": device_rows,
        "threshold_rules": threshold_rules,
        "device_create_url": reverse(
            "dashboard:device-create",
            kwargs={"asset_code": asset.code},
        ),
        "device_attach_url": reverse(
            "dashboard:device-attach",
            kwargs={"asset_code": asset.code},
        ),
        "detail_url": reverse(
            "dashboard:asset-detail",
            kwargs={"asset_identifier": asset.code},
        ),
        "attachable_device_count": Device.objects.filter(
            site=asset.site, asset__isnull=True,
        ).count(),
    })


# ── Stage 2a: Device create ─────────────────────────────────────────────────

class DeviceCreateStageView(LoginRequiredMixin, View):
    template_name = "dashboard/device_create.html"

    def get(self, request, asset_code: str):
        asset = _get_asset_or_404(asset_code)
        return render(request, self.template_name, {
            "asset": asset, "form": DeviceCreateStageForm(),
        })

    def post(self, request, asset_code: str):
        asset = _get_asset_or_404(asset_code)
        form = DeviceCreateStageForm(request.POST)
        if not form.is_valid():
            return render(request, self.template_name, {
                "asset": asset, "form": form, "has_errors": True,
            }, status=400)
        try:
            device = self._commit(asset, form)
        except Exception as exc:  # noqa: BLE001
            form.add_error(None, str(exc))
            return render(request, self.template_name, {
                "asset": asset, "form": form, "has_errors": True,
            }, status=400)
        messages.success(
            request,
            f"Ierīce '{device.device_uid}' pievienota aktīvam '{asset.code}'.",
        )
        return redirect(
            reverse("dashboard:asset-configure",
                    kwargs={"asset_code": asset.code})
        )

    @transaction.atomic
    def _commit(self, asset: Asset, form: DeviceCreateStageForm) -> Device:
        cd = form.cleaned_data
        return create_device_with_unique_uid(
            site=asset.site,
            asset=asset,
            name=cd["name"].strip(),
            device_type=(cd.get("device_type") or "").strip(),
            is_simulated=bool(cd.get("is_simulated")),
            expected_interval_seconds=(cd.get("expected_interval_seconds") or 60),
            firmware_version=(cd.get("firmware_version") or "").strip(),
            status=cd.get("status") or "unknown",
        )


# ── Stage 2b: Device attach ─────────────────────────────────────────────────

class DeviceAttachStageView(LoginRequiredMixin, View):
    template_name = "dashboard/device_attach.html"

    def get(self, request, asset_code: str):
        asset = _get_asset_or_404(asset_code)
        return render(request, self.template_name, {
            "asset": asset, "form": DeviceAttachStageForm(asset=asset),
        })

    def post(self, request, asset_code: str):
        asset = _get_asset_or_404(asset_code)
        form = DeviceAttachStageForm(request.POST, asset=asset)
        if not form.is_valid():
            return render(request, self.template_name, {
                "asset": asset, "form": form, "has_errors": True,
            }, status=400)
        device = form.cleaned_data["existing_device"]
        with transaction.atomic():
            # Re-check inside the transaction to guard against another
            # operator claiming the same device between page load and POST.
            device.refresh_from_db()
            if device.asset_id is not None or device.site_id != asset.site_id:
                form.add_error(
                    "existing_device",
                    "Ierīces stāvoklis ir mainījies — pārlādējiet lapu.",
                )
                return render(request, self.template_name, {
                    "asset": asset, "form": form, "has_errors": True,
                }, status=400)
            device.asset = asset
            device.save(update_fields=["asset", "updated_at"])
        messages.success(
            request,
            f"Ierīce '{device.device_uid}' piesaistīta aktīvam '{asset.code}'.",
        )
        return redirect(
            reverse("dashboard:asset-configure",
                    kwargs={"asset_code": asset.code})
        )


# ── Stage 3: Sensor create ──────────────────────────────────────────────────

class SensorCreateStageView(LoginRequiredMixin, View):
    template_name = "dashboard/sensor_create.html"

    def get(self, request, asset_code: str, device_uid: str):
        asset = _get_asset_or_404(asset_code)
        device = _get_device_or_404(asset, device_uid)
        return render(request, self.template_name, {
            "asset": asset, "device": device, "form": SensorCreateStageForm(),
        })

    def post(self, request, asset_code: str, device_uid: str):
        asset = _get_asset_or_404(asset_code)
        device = _get_device_or_404(asset, device_uid)
        form = SensorCreateStageForm(request.POST)
        if not form.is_valid():
            return render(request, self.template_name, {
                "asset": asset, "device": device,
                "form": form, "has_errors": True,
            }, status=400)
        try:
            sensor, preset_metric = self._commit(device, form)
        except Exception as exc:  # noqa: BLE001
            form.add_error(None, str(exc))
            return render(request, self.template_name, {
                "asset": asset, "device": device,
                "form": form, "has_errors": True,
            }, status=400)
        messages.success(
            request,
            f"Sensors '{sensor.code}' pievienots ierīcei '{device.device_uid}'.",
        )
        # If the operator selected a preset, jump straight to Stage 4
        # with the preset pre-applied; otherwise return to the hub.
        if preset_metric is not None:
            return redirect(
                reverse(
                    "dashboard:sensor-metric-create",
                    kwargs={
                        "asset_code": asset.code,
                        "device_uid": device.device_uid,
                        "sensor_code": sensor.code,
                    },
                )
                + f"?preset={preset_metric}"
            )
        return redirect(
            reverse(
                "dashboard:sensor-metric-create",
                kwargs={
                    "asset_code": asset.code,
                    "device_uid": device.device_uid,
                    "sensor_code": sensor.code,
                },
            )
        )

    @transaction.atomic
    def _commit(self, device: Device, form: SensorCreateStageForm):
        cd = form.cleaned_data
        preset = cd.get("preset")
        sensor_name = (cd.get("name") or "").strip()
        sensor_type = (cd.get("sensor_type") or "").strip()
        description = (cd.get("description") or "").strip()
        preset_metric_code = None
        if preset is not None:
            # Preset fills in any blanks the operator left.
            if not sensor_name:
                sensor_name = (preset.default_sensor_name or preset.name).strip()
            if not sensor_type:
                sensor_type = (preset.sensor_type or "").strip()
            if not description:
                description = preset.description
            preset_metric_code = preset.code
        sensor = create_sensor_with_unique_code(
            device=device,
            name=sensor_name,
            sensor_type=sensor_type,
            description=description,
        )
        return sensor, preset_metric_code


# ── Stage 4: SensorMetric (+ ThresholdRule) ─────────────────────────────────

class SensorMetricStageView(LoginRequiredMixin, View):
    template_name = "dashboard/sensor_metric_create.html"

    def get(self, request, asset_code: str, device_uid: str, sensor_code: str):
        asset = _get_asset_or_404(asset_code)
        device = _get_device_or_404(asset, device_uid)
        sensor = _get_sensor_or_404(device, sensor_code)
        initial = {}
        preset_code = request.GET.get("preset")
        if preset_code:
            from apps.iot_config.models import SensorMetricPreset
            preset = SensorMetricPreset.objects.filter(code=preset_code).first()
            if preset is not None:
                initial = {
                    "metric_mode": METRIC_MODE_PRESET,
                    "sensor_metric_preset": preset.pk,
                    "sensor_metric_is_required": preset.is_required,
                    "sensor_metric_sort_order": preset.sort_order,
                }
        form = SensorMetricStageForm(initial=initial, sensor=sensor)
        return render(request, self.template_name, {
            "asset": asset, "device": device, "sensor": sensor, "form": form,
        })

    def post(self, request, asset_code: str, device_uid: str, sensor_code: str):
        asset = _get_asset_or_404(asset_code)
        device = _get_device_or_404(asset, device_uid)
        sensor = _get_sensor_or_404(device, sensor_code)
        form = SensorMetricStageForm(request.POST, sensor=sensor)
        if not form.is_valid():
            return render(request, self.template_name, {
                "asset": asset, "device": device, "sensor": sensor,
                "form": form, "has_errors": True,
            }, status=400)
        try:
            self._commit(asset, device, sensor, form)
        except Exception as exc:  # noqa: BLE001
            form.add_error(None, str(exc))
            return render(request, self.template_name, {
                "asset": asset, "device": device, "sensor": sensor,
                "form": form, "has_errors": True,
            }, status=400)
        messages.success(
            request,
            f"Metrika veiksmīgi piesaistīta sensoram '{sensor.code}'.",
        )
        return redirect(
            reverse("dashboard:asset-configure",
                    kwargs={"asset_code": asset.code})
        )

    @transaction.atomic
    def _commit(
        self,
        asset: Asset,
        device: Device,
        sensor: Sensor,
        form: SensorMetricStageForm,
    ):
        metric, _ = form.resolved_metric()
        SensorMetric.objects.create(
            sensor=sensor,
            metric=metric,
            is_required=bool(form.cleaned_data.get("sensor_metric_is_required")),
            sort_order=form.cleaned_data.get("sensor_metric_sort_order") or 0,
        )
        self._maybe_create_threshold_rule(
            form=form, asset=asset, device=device, sensor=sensor, metric=metric,
        )

    @staticmethod
    def _maybe_create_threshold_rule(*, form, asset, device, sensor, metric):
        """
        Materialise either the chosen ``ThresholdRulePreset`` or the
        operator's manual entry into a concrete ``ThresholdRule``.

        Scope is now an explicit, operator-visible choice on the form
        (``threshold_scope_level``). The natural default remains
        ``sensor`` because we're on a sensor configuration page, but the
        operator can broaden the scope to device / asset / site / global
        here without dropping into Django admin. The chosen scope
        determines which FKs we attach; model-level ``clean()`` then
        auto-fills higher-level FKs from the chosen target for
        consistency.
        """
        from apps.analytics.models import ThresholdRuleScope

        cd = form.cleaned_data
        mode = cd.get("threshold_mode") or THRESHOLD_MODE_NONE
        if mode == THRESHOLD_MODE_NONE:
            return None

        scope_level = (
            cd.get("threshold_scope_level") or ThresholdRuleScope.SENSOR
        )
        scope_fks = SensorMetricStageView._scope_fks_for(
            scope_level,
            asset=asset, device=device, sensor=sensor,
        )

        if mode == THRESHOLD_MODE_PRESET:
            preset = cd["threshold_preset"]
            return create_threshold_rule_with_unique_code(
                name=preset.name,
                description=preset.description,
                metric=preset.metric,
                scope_level=scope_level,
                lower_bound=preset.lower_bound,
                upper_bound=preset.upper_bound,
                severity=preset.severity,
                close_when_normal=preset.close_when_normal,
                **scope_fks,
            )
        # Manual.
        return create_threshold_rule_with_unique_code(
            name=cd["threshold_name"].strip(),
            description=(cd.get("threshold_description") or "").strip(),
            metric=metric,
            scope_level=scope_level,
            lower_bound=cd.get("threshold_lower_bound"),
            upper_bound=cd.get("threshold_upper_bound"),
            severity=cd.get("threshold_severity") or "warning",
            close_when_normal=bool(cd.get("threshold_close_when_normal")),
            **scope_fks,
        )

    @staticmethod
    def _scope_fks_for(scope_level, *, asset, device, sensor):
        """
        Map a chosen ``scope_level`` to the FK shape ``ThresholdRule``
        expects. Pages that anchor on a sensor have the full chain
        available, so each scope simply picks the right subset.
        """
        from apps.analytics.models import ThresholdRuleScope

        if scope_level == ThresholdRuleScope.SENSOR:
            return {
                "site": asset.site, "asset": asset,
                "device": device, "sensor": sensor,
            }
        if scope_level == ThresholdRuleScope.DEVICE:
            return {
                "site": asset.site, "asset": asset,
                "device": device, "sensor": None,
            }
        if scope_level == ThresholdRuleScope.ASSET:
            return {
                "site": asset.site, "asset": asset,
                "device": None, "sensor": None,
            }
        if scope_level == ThresholdRuleScope.SITE:
            return {
                "site": asset.site, "asset": None,
                "device": None, "sensor": None,
            }
        # GLOBAL: no scope FKs.
        return {"site": None, "asset": None, "device": None, "sensor": None}


def health_view(request):
    """Tiny dashboard liveness probe — independent of the data API."""
    return HttpResponse("ok", content_type="text/plain")


# ── Phase 7 bugfix: ThresholdRule edit page ─────────────────────────────────

def _get_threshold_rule_or_404(asset, rule_code: str):
    """
    Fetch a ``ThresholdRule`` that is **reachable from this asset**:

      * sensor-scope rules whose ``sensor.device.asset == asset``;
      * device-scope rules whose ``device.asset == asset``;
      * asset-scope rules whose ``asset == asset``;
      * site-scope rules whose ``site == asset.site``.

    Global rules and rules belonging to other assets/sites are intentionally
    out of scope for the dashboard edit page; they remain editable via
    Django admin.
    """
    from django.db.models import Q
    from apps.analytics.models import ThresholdRuleScope

    qs = ThresholdRule.objects.select_related(
        "metric", "sensor", "sensor__device",
        "device", "asset", "site",
    ).filter(
        Q(
            scope_level=ThresholdRuleScope.SENSOR,
            sensor__device__asset=asset,
        )
        | Q(
            scope_level=ThresholdRuleScope.DEVICE,
            device__asset=asset,
        )
        | Q(scope_level=ThresholdRuleScope.ASSET, asset=asset)
        | Q(scope_level=ThresholdRuleScope.SITE, site=asset.site),
    )
    rule = qs.filter(code=rule_code).first()
    if rule is None:
        raise Http404(
            f"ThresholdRule '{rule_code}' is not reachable from asset "
            f"'{asset.code}'.",
        )
    return rule


class ThresholdRuleEditView(LoginRequiredMixin, View):
    """
    Operator-facing edit form for one :class:`ThresholdRule`, anchored to
    an asset so we only expose rules already reachable from that asset.

    Promotion to global scope is intentionally not exposed here — that
    would silently change semantics on a wide set of assets/sensors and
    belongs to Django admin.
    """

    template_name = "dashboard/threshold_rule_edit.html"

    def get(self, request, asset_code: str, rule_code: str):
        asset = _get_asset_or_404(asset_code)
        rule = _get_threshold_rule_or_404(asset, rule_code)
        form = ThresholdRuleEditForm(
            asset=asset, instance=rule,
            initial=ThresholdRuleEditForm.initial_from(rule),
        )
        return render(request, self.template_name, {
            "asset": asset, "rule": rule, "form": form,
            "scope_choices": THRESHOLD_SCOPE_CHOICES,
        })

    def post(self, request, asset_code: str, rule_code: str):
        asset = _get_asset_or_404(asset_code)
        rule = _get_threshold_rule_or_404(asset, rule_code)
        form = ThresholdRuleEditForm(
            request.POST, asset=asset, instance=rule,
        )
        if not form.is_valid():
            return render(request, self.template_name, {
                "asset": asset, "rule": rule, "form": form,
                "scope_choices": THRESHOLD_SCOPE_CHOICES,
                "has_errors": True,
            }, status=400)
        try:
            self._commit(form, rule)
        except Exception as exc:  # noqa: BLE001
            # Surface model-level ValidationError messages back into the
            # form so operators see *why* a save was rejected (e.g.,
            # sensor-scope rule with missing SensorMetric).
            form.add_error(None, str(exc))
            return render(request, self.template_name, {
                "asset": asset, "rule": rule, "form": form,
                "scope_choices": THRESHOLD_SCOPE_CHOICES,
                "has_errors": True,
            }, status=400)
        messages.success(
            request,
            f"Sliekšņa noteikums '{rule.code}' atjaunināts.",
        )
        return redirect(
            reverse("dashboard:asset-configure",
                    kwargs={"asset_code": asset.code})
        )

    @transaction.atomic
    def _commit(self, form, rule):
        form.apply_to(rule)
        rule.save()


# ── Phase 7, Task 4A: Events & Anomaly Review ───────────────────────────────
#
# The events pages are read-only operator surfaces. They render a thin
# server-side shell and delegate data loading to the read-only
# ``/api/events/`` and ``/api/measurements/`` endpoints. Acknowledge/close
# actions are explicitly *not* implemented in this task; the views are
# strict GET-only TemplateViews so the dashboard tests can assert that
# POSTs return 405 without any side effects.

# Period buttons offered on the event detail timeline. Kept on the
# server side so the dashboard tests can pin the exact set without
# scraping JavaScript. JS reads the order from the config block.
EVENT_TIMELINE_PERIODS = (
    {"id": "1h", "label": "1h", "hours": 1},
    {"id": "6h", "label": "6h", "hours": 6},
    {"id": "24h", "label": "24h", "hours": 24},
    {"id": "7d", "label": "7d", "hours": 24 * 7},
    {"id": "all", "label": "Visi", "hours": None},
)


class EventsListView(LoginRequiredMixin, TemplateView):
    """Server-rendered shell for ``GET /dashboard/events/``.

    The page is GET-only and renders an empty filter form + table; the
    actual rows are fetched client-side from ``/api/events/`` so server
    and dashboard cannot drift apart on filter semantics.
    """

    template_name = "dashboard/events_list.html"
    http_method_names = ["get", "head", "options"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["event_type_choices"] = EventType.choices
        context["severity_choices"] = Severity.choices
        context["event_status_choices"] = EventStatus.choices
        context["default_limit"] = 100
        context["max_limit"] = 1000
        context["events_list_config"] = {
            "endpoints": {
                "events": reverse("event-list"),
            },
            "eventDetailUrlTemplate": reverse(
                "dashboard:event-detail",
                kwargs={"event_id": "00000000-0000-0000-0000-000000000000"},
            ).replace(
                "00000000-0000-0000-0000-000000000000", "__ID__",
            ),
            "assetDetailUrlTemplate": reverse(
                "dashboard:asset-detail",
                kwargs={"asset_identifier": "__CODE__"},
            ),
            "defaultLimit": 100,
            "maxLimit": 1000,
            # Server-side enums help the JS validate filter values
            # before sending a request that would 400.
            "choices": {
                "status": list(EventStatus.values),
                "event_type": list(EventType.values),
                "severity": list(Severity.values),
            },
        }
        return context


class EventDetailView(LoginRequiredMixin, TemplateView):
    """Server-rendered shell for ``GET /dashboard/events/<event_id>/``.

    The view itself only validates that the event exists (so unknown
    UUIDs return 404) and emits a small config block; the rest of the
    page — context, payload JSON, measurement summary, sensor/metric
    timeline — is loaded client-side from ``/api/events/<id>/`` and
    ``/api/measurements/``.
    """

    template_name = "dashboard/event_detail.html"
    http_method_names = ["get", "head", "options"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        event_id = kwargs["event_id"]
        # 404 surface so test_unknown_event_id_returns_404 holds. We
        # don't need any of the actual fields here because the page is
        # rendered client-side; but verifying existence keeps the URL
        # honest and avoids a flashing-then-broken page.
        event = get_object_or_404(
            Event.objects.only("id"), id=event_id,
        )
        context["event_id"] = str(event.id)
        # URL templates for the JS side. Both use UUID-shaped placeholders
        # so the JS does not have to special-case path segments.
        event_detail_url = reverse("event-detail", kwargs={"pk": str(event.id)})
        measurements_list_url = reverse("measurement-list")
        context["event_detail_config"] = {
            "eventId": str(event.id),
            "eventDetailUrl": event_detail_url,
            "measurementsUrl": measurements_list_url,
            "eventsListUrl": reverse("dashboard:events-list"),
            "assetDetailUrlTemplate": reverse(
                "dashboard:asset-detail",
                kwargs={"asset_identifier": "__CODE__"},
            ),
            "periods": list(EVENT_TIMELINE_PERIODS),
            "defaultPeriod": "24h",
            "timelineLimit": 1000,
        }
        return context
