# Generated by Django 5.2.14 on 2026-05-16 18:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('iot_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('code', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('lower_bound', models.FloatField(blank=True, null=True)),
                ('upper_bound', models.FloatField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='warning', max_length=16)),
                ('message_template', models.TextField(blank=True)),
                ('close_when_normal', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threshold_rules', to='assets.asset')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threshold_rules', to='assets.device')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='threshold_rules', to='iot_config.metricdefinition')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threshold_rules', to='assets.site')),
            ],
            options={
                'verbose_name': 'Threshold Rule',
                'verbose_name_plural': 'Threshold Rules',
                'ordering': ['sort_order', 'code'],
                'indexes': [models.Index(fields=['is_enabled'], name='analytics_t_is_enab_fe81c8_idx'), models.Index(fields=['metric'], name='analytics_t_metric__ddc332_idx'), models.Index(fields=['site', 'metric'], name='analytics_t_site_id_4725e4_idx'), models.Index(fields=['asset', 'metric'], name='analytics_t_asset_i_bf3c41_idx'), models.Index(fields=['device', 'metric'], name='analytics_t_device__cc900e_idx')],
            },
        ),
    ]
