# Generated by Django 5.2.14 on 2026-05-17 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('assets', '0001_initial'),
        ('iot_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thresholdrule',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threshold_rules', to='assets.sensor'),
        ),
        migrations.AddIndex(
            model_name='thresholdrule',
            index=models.Index(fields=['sensor', 'metric'], name='analytics_t_sensor__4f9b26_idx'),
        ),
    ]
