# Generated by Django 5.2.14 on 2026-05-17 12:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_thresholdrule_sensor_and_more'),
        ('iot_config', '0002_sensormetricpreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdRulePreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('code', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('lower_bound', models.FloatField(blank=True, null=True)),
                ('upper_bound', models.FloatField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='warning', max_length=16)),
                ('close_when_normal', models.BooleanField(default=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='threshold_rule_presets', to='iot_config.metricdefinition')),
            ],
            options={
                'verbose_name': 'Threshold Rule Preset',
                'verbose_name_plural': 'Threshold Rule Presets',
                'ordering': ['code'],
            },
        ),
    ]
