# Generated by Django 5.2.14 on 2026-05-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_thresholdrulepreset'),
        ('assets', '0002_sensormetric_sensor_metrics_and_more'),
        ('iot_config', '0002_sensormetricpreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='thresholdrule',
            name='scope_level',
            field=models.CharField(choices=[('global', 'Global'), ('site', 'Site'), ('asset', 'Asset'), ('device', 'Device'), ('sensor', 'Sensor')], db_index=True, default='sensor', max_length=16),
        ),
        migrations.AddIndex(
            model_name='thresholdrule',
            index=models.Index(fields=['scope_level', 'metric'], name='analytics_t_scope_l_b306c1_idx'),
        ),
    ]
