# Generated by Django 5.2.14 on 2026-05-16 14:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('iot_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source_type', models.CharField(choices=[('mqtt', 'MQTT'), ('rest', 'REST'), ('simulator', 'Simulator'), ('manual', 'Manual'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('topic', models.CharField(blank=True, max_length=512)),
                ('payload', models.JSONField(default=dict)),
                ('payload_text', models.TextField(blank=True)),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('device_uid', models.CharField(blank=True, db_index=True, max_length=128)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('payload_timestamp', models.DateTimeField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('received', 'Received'), ('parsed', 'Parsed'), ('failed', 'Failed'), ('ignored', 'Ignored'), ('duplicate', 'Duplicate')], db_index=True, default='received', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('parser_version', models.CharField(blank=True, max_length=32)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_messages', to='assets.asset')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_messages', to='assets.device')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_messages', to='assets.site')),
            ],
            options={
                'verbose_name': 'Raw Message',
                'verbose_name_plural': 'Raw Messages',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('value_float', models.FloatField(blank=True, null=True)),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_text', models.CharField(blank=True, max_length=512)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('quality', models.CharField(choices=[('good', 'Good'), ('estimated', 'Estimated'), ('invalid', 'Invalid'), ('missing', 'Missing'), ('unknown', 'Unknown')], default='good', max_length=16)),
                ('is_anomalous', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='assets.asset')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to='assets.device')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='iot_config.metricdefinition')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to='assets.sensor')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='assets.site')),
                ('raw_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to='telemetry.rawmessage')),
            ],
            options={
                'verbose_name': 'Measurement',
                'verbose_name_plural': 'Measurements',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='rawmessage',
            index=models.Index(fields=['source_type'], name='telemetry_r_source__e13041_idx'),
        ),
        migrations.AddConstraint(
            model_name='rawmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('message_id__gt', '')), fields=('message_id',), name='unique_rawmessage_message_id_nonempty'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['site', 'timestamp'], name='telemetry_m_site_id_0306b2_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['asset', 'timestamp'], name='telemetry_m_asset_i_a793a4_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['device', 'timestamp'], name='telemetry_m_device__42ea83_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['metric', 'timestamp'], name='telemetry_m_metric__ea7594_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['asset', 'metric', 'timestamp'], name='telemetry_m_asset_i_108c4d_idx'),
        ),
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.UniqueConstraint(condition=models.Q(('raw_message__isnull', False)), fields=('raw_message', 'metric'), name='unique_measurement_raw_message_metric'),
        ),
    ]
