# Generated by Django 5.2.14 on 2026-05-16 14:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('device_type', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('default_expected_interval_seconds', models.PositiveIntegerField(default=60)),
            ],
            options={
                'verbose_name': 'Device Profile',
                'verbose_name_plural': 'Device Profiles',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('data_type', models.CharField(choices=[('float', 'Float'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('string', 'String')], default='float', max_length=16)),
                ('normal_min', models.FloatField(blank=True, null=True)),
                ('normal_max', models.FloatField(blank=True, null=True)),
                ('warning_min', models.FloatField(blank=True, null=True)),
                ('warning_max', models.FloatField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Metric Definition',
                'verbose_name_plural': 'Metric Definitions',
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='DeviceProfileMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_metrics', to='iot_config.deviceprofile')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_metrics', to='iot_config.metricdefinition')),
            ],
            options={
                'verbose_name': 'Device Profile Metric',
                'verbose_name_plural': 'Device Profile Metrics',
                'ordering': ['sort_order', 'metric__key'],
            },
        ),
        migrations.AddField(
            model_name='deviceprofile',
            name='metrics',
            field=models.ManyToManyField(blank=True, related_name='device_profiles', through='iot_config.DeviceProfileMetric', to='iot_config.metricdefinition'),
        ),
        migrations.CreateModel(
            name='MqttTopicTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=128)),
                ('topic_type', models.CharField(choices=[('telemetry', 'Telemetry'), ('status', 'Status'), ('event', 'Event'), ('command', 'Command'), ('command_ack', 'Command Ack')], max_length=16)),
                ('template', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'MQTT Topic Template',
                'verbose_name_plural': 'MQTT Topic Templates',
                'ordering': ['topic_type', 'name'],
                'constraints': [models.UniqueConstraint(fields=('topic_type', 'name'), name='unique_mqtt_topic_template_type_name')],
            },
        ),
        migrations.AddConstraint(
            model_name='deviceprofilemetric',
            constraint=models.UniqueConstraint(fields=('profile', 'metric'), name='unique_device_profile_metric'),
        ),
    ]
