# Generated by Django 5.2.14 on 2026-05-17 12:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorMetricPreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('sensor_type', models.CharField(blank=True, max_length=64)),
                ('default_sensor_name', models.CharField(blank=True, max_length=256)),
                ('default_unit', models.CharField(blank=True, max_length=32)),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensor_metric_presets', to='iot_config.metricdefinition')),
            ],
            options={
                'verbose_name': 'Sensor Metric Preset',
                'verbose_name_plural': 'Sensor Metric Presets',
                'ordering': ['sort_order', 'code'],
            },
        ),
    ]
